[build-system]
requires = ["setuptools>=42", "python-semantic-release>=10.0.1","wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"

[project]
name = "autosec"
description = "A collection of utilities for security operations and automation."
authors = [
    {name = "Dylan Diamond", email = "dylandiamond1997@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography",
    "python-dotenv",
    "requests"

]

[project.urls]
"Homepage" = "https://github.com/dylandiamond97/autosec"

[project.scripts]
autocred = "autosec.cli:autocred_cli"
autolog = "autosec.cli:autolog_cli"

[tool.setuptools.packages.find]
include = ["autosec"]
exclude = ["gitignore", "Sample Uses"]
