name: Publish to PyPI

on:
  push:
    branches:
      - main

permissions:
  id-token: write       # Required for OIDC auth to PyPI
  contents: read        # Required to checkout code

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi         # Must match the environment name registered on PyPI

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release build twine setuptools_scm

      - name: Run semantic release
        run: semantic-release publish

#      - name: Build package
#        run: python -m build
#
#      - name: Publish to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
# again