name: Publish to PyPI

on:
  push:
    branches:
      - main

permissions:
  contents: write        # needed to push tags
  id-token: write        # OIDC token for PyPI auth
  packages: write        # publish packages

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full git history needed for version calculation

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install python-semantic-release

      - name: Install project dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run semantic-release
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release -vv publish
